version: "3.3"
services:
  chrome-2:
      image: selenium/node-chrome:114.0
      shm_size: 1gb  
      depends_on:
        - selenium-hub
      environment:
        - SE_EVENT_BUS_HOST=selenium-hub
        - SE_EVENT_BUS_PUBLISH_PORT=4442
        - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
        - SE_NODE_MAX_SESSIONS=1
        - SE_NODE_MAX_INSTANCES=1
        - SE_NODE_SESSION_TIMEOUT=100
  chrome:
    image: selenium/node-chrome:114.0
    shm_size: 1gb  
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=6
      - SE_NODE_MAX_INSTANCES=6
      - SE_NODE_SESSION_TIMEOUT=100
    
  chrome-3:
    image: selenium/node-chrome:114.0
    shm_size: 1gb  
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=6
      - SE_NODE_MAX_INSTANCES=6
      - SE_NODE_SESSION_TIMEOUT=100
  chrome-4:
    image: selenium/node-chrome:114.0
    shm_size: 1gb  
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=6
      - SE_NODE_MAX_INSTANCES=6
      - SE_NODE_SESSION_TIMEOUT=100
  chrome-5:
    image: selenium/node-chrome:114.0
    shm_size: 1gb  
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=6
      - SE_NODE_MAX_INSTANCES=6
      - SE_NODE_SESSION_TIMEOUT=100

  selenium-hub:
    image: selenium/hub:4.10.0
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"